site_name: Alice CodeCreator 中文参考文档
theme: readthedocs
use_directory_urls: true
site_url: https://creator.liuxp.me
site_author: 刘小平
repo_url: https://github.com/lxp135/alice-code-creator-docs
copyright: Alice CodeCreator 中文参考文档由<a href="https://liuxp.me">刘小平</a>提供，项目托管在<a href="https://github.com/lxp135/alice-code-creator-docs">GitHub</a>。<script type="text/javascript" src="https://js.users.51.la/18564708.js"></script>

pages:
- '首页': 'index.md'
- '更新日志': 'released.md'
- '用户手册':
  - '快速开始': 'users/getting-started.md'
  - '数据类型配置': 'users/data-type.md'
  - '数据源配置': 'users/data-source.md'
  - '模板配置': 'users/template.md'
  - '生成代码': 'users/generator.md'
- '开发者手册':
  - '开发计划': 'developers/plan.md'
  - '构建与运行': 'developers/building.md'
  - '软件结构介绍': 'developers/framework.md'
  - '贡献代码': 'developers/writing-code.md'
  - '编写文档': 'developers/writing-documents.md'
  - '贡献者列表': 'developers/contributors-of-documents.md'
- '参考资料':
  - 'FAQ': 'references/FAQ.md'

markdown_extensions:
    - markdown.extensions.toc
    - markdown.extensions.admonition
    - markdown.extensions.smarty
    - markdown.extensions.nl2br
    - markdown.extensions.codehilite:
        guess_lang: false